site:
  title: Terry Moore II
  description: A personal blog
  url: https://terrymooreii.github.io/sia-blog
  author: Terry Moore II
theme: 
  name: minimal
  showHero: true
  
input: src
output: dist
layouts: _layouts
includes: _includes
collections:
  posts:
    path: posts
    layout: post
    permalink: /blog/:slug/
    sortBy: date
    sortOrder: desc
  pages:
    path: pages
    layout: page
    permalink: /:slug/
  notes:
    path: notes
    layout: note
    permalink: /notes/:slug/
    sortBy: date
    sortOrder: desc
pagination:
  size: 10
server:
  port: 3000
  showDrafts: true
