site:
  title: Terry Moore II
  description: My corner of the internet
  url: https://terrymooreii.github.io/sia-blog
  author: Terry Moore II
  
theme: 
  name: minimal
  showHero: true

plugins:
  enabled: true
  config:
    sia-plugin-lightbox:
      enabled: true
    sia-plugin-scroll-progress:
      enabled: true
      height: "4px"
      color: "#3498db"
      position: "top"
      zIndex: 10000

assets:
  css:
    - styles/custom.css
  
input: src
output: dist
layouts: _layouts
includes: _includes
collections:
  posts:
    path: posts/:year/:month
    layout: post
    permalink: /blog/:year/:month/:slug/
    sortBy: date
    sortOrder: desc
  pages:
    path: pages
    layout: page
    permalink: /:slug/
  notes:
    path: notes/:year/:month
    layout: note
    permalink: /notes/:year/:month/:day/:slug/
    sortBy: date
    sortOrder: desc
pagination:
  size: 10
server:
  port: 3000
  showDrafts: true
